<a href="https://colab.research.google.com/github/ariyan378/Data-Analytics-Ml/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)

2.2.2

> ## **Series**

In [2]:
#creating Series
s= pd.Series(['Hridoy' , 'Himu' ])
print(s)

0    Hridoy
1      Himu
dtype: object

In [3]:
#custom index
singer = pd.Series(['Don Toliver' , 'Travis Scott' ,'Future' , "Playboi Carti"] , index=[1,2,3,4])
print(s)

0    Hridoy
1      Himu
dtype: object

In [4]:
#from dictionary

dictionary = {
    1:"No Idea",
    2:"Fein",
    3:"Mask Off",
    4:"Timeless"

}

song = pd.Series(dictionary)
print(song)

1     No Idea
2        Fein
3    Mask Off
4    Timeless
dtype: object

> ## **Data Frame**

In [5]:
# Creating DataFrame from dictionary
data = {
    'Name': ['Himu', 'Hridoy', 'Moon Knight'],
    'Age': [24, 30, 35],
    'City': ['Mirpur', 'Dhaka', 'New York']
}
df = pd.DataFrame(data)
df

          Name  Age      City
0         Himu   24    Mirpur
1       Hridoy   30     Dhaka
2  Moon Knight   35  New York

In [6]:

# From  List
lists = [['Hridoy', 'Data Science'],['Himu' , 'ML Engineer']]
df = pd.DataFrame(data = lists , columns = ['Name' , 'Dream'])
df

     Name         Dream
0  Hridoy  Data Science
1    Himu   ML Engineer

In [7]:
arr = np.arange(1,17).reshape(4,4)
np_df = pd.DataFrame(arr)
np_df

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

> # **Practice Dataset**

In [8]:
#practice dataset
import pandas as pd

# Define the Moon Knight dataset
moon_knight_data = {
    "ID": list(range(1, 15)),
    "Entity Name": [
        "Marc Spector",
        "Steven Grant",
        "Jake Lockley",
        "Khonshu",
        "Taweret",
        "Ammit",
        "Arthur Harrow",
        "Layla El-Faouly",
        "Scarlet Scarab",
        "Anton Mogart",
        "Crescent Darts",
        "Suit of Armor",
        "Scarab of Ammit",
        "Ushebti",
    ],
    "Type": [
        "Alter / Avatar",
        "Alter",
        "Alter",
        "Ennead Deity",
        "Ennead Deity",
        "Ennead Deity",
        "Avatar / Antagonist",
        "Ally",
        "Superhero Identity",
        "Antagonist",
        "Weapon",
        "Equipment",
        "Relic",
        "Relic",
    ],
    "Role / Affiliation": [
        "Primary Avatar of Khonshu",
        "Gift Shop Clerk / Egyptologist",
        "Ruthless Taxi Driver Alter",
        "Egyptian God of the Moon",
        "Egyptian Goddess of Childbirth",
        "Egyptian Devourer of Souls",
        "Leader of Ammit Cult",
        "Archeologist / Marc's Wife",
        "Avatar of Taweret",
        "Antiquities Collector",
        "Primary Throwing Weapon",
        "Ceremonial Armor of Khonshu",
        "Compass to Ammit's Tomb",
        "Stone Idol for Bound Deities",
    ],
    "First MCU Appearance": [
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 6)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 4)",
        "Moon Knight (Ep 6)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 2)",
        "Moon Knight (Ep 6)",
        "Moon Knight (Ep 3)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 2)",
        "Moon Knight (Ep 3)",
    ],
    "Status": [
        "Active",
        "Active",
        "Active",
        "Active",
        "Active",
        "Deceased / Sealed",
        "Deceased",
        "Active",
        "Active",
        "Deceased",
        "Active",
        "Active",
        "Destroyed",
        "Active",
    ],
}

# Create DataFrame
df = pd.DataFrame(moon_knight_data)


df.head(2)
# Export to CSV option
# df.to_csv("moon_knight_dataset.csv", index=False)

,ID,Entity Name,Type,Role / Affiliation,First MCU Appearance,Status
0,1,Marc Spector,Alter / Avatar,Primary Avatar of Khonshu,Moon Knight (Ep 1),Active
1,2,Steven Grant,Alter,Gift Shop Clerk / Egyptologist,Moon Knight (Ep 1),Active

In [9]:
print(df.shape)
print(df.columns.to_list())
print(df.size)
print(df.index)
print(df.dtypes)
print(df.info())
print(df.describe(include=['object']))
print(df.ndim)

(14, 6)
['ID', 'Entity Name', 'Type', 'Role / Affiliation', 'First MCU Appearance', 'Status']
84
RangeIndex(start=0, stop=14, step=1)
ID                       int64
Entity Name             object
Type                    object
Role / Affiliation      object
First MCU Appearance    object
Status                  object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    14 non-null     int64
 1   Entity Name           14 non-null     object
 2   Type                  14 non-null     object
 3   Role / Affiliation    14 non-null     object
 4   First MCU Appearance  14 non-null     object
 5   Status                14 non-null     object
dtypes: int64(1), object(5)
memory usage: 804.0+ bytes
None
         Entity Name          Type         Role / Affiliation  \
count             14            14                         14
unique            14            10                         14
top     Marc Spector  Ennead Deity  Primary Avatar of Khonshu
freq               1             3                          1

       First MCU Appearance  Status
count                    14      14
unique                    5       4
top      Moon Knight (Ep 1)  Active
freq                      6      10
2

> ## **Index & Columns Overview**

In [10]:
#row
df.index

RangeIndex(start=0, stop=14, step=1)

In [11]:
df.index.to_list()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [12]:
#view col
df.columns.to_list()

['ID',
 'Entity Name',
 'Type',
 'Role / Affiliation',
 'First MCU Appearance',
 'Status']

In [13]:
df.values

array([[1, 'Marc Spector', 'Alter / Avatar', 'Primary Avatar of Khonshu',
        'Moon Knight (Ep 1)', 'Active'],
       [2, 'Steven Grant', 'Alter', 'Gift Shop Clerk / Egyptologist',
        'Moon Knight (Ep 1)', 'Active'],
       [3, 'Jake Lockley', 'Alter', 'Ruthless Taxi Driver Alter',
        'Moon Knight (Ep 6)', 'Active'],
       [4, 'Khonshu', 'Ennead Deity', 'Egyptian God of the Moon',
        'Moon Knight (Ep 1)', 'Active'],
       [5, 'Taweret', 'Ennead Deity', 'Egyptian Goddess of Childbirth',
        'Moon Knight (Ep 4)', 'Active'],
       [6, 'Ammit', 'Ennead Deity', 'Egyptian Devourer of Souls',
        'Moon Knight (Ep 6)', 'Deceased / Sealed'],
       [7, 'Arthur Harrow', 'Avatar / Antagonist',
        'Leader of Ammit Cult', 'Moon Knight (Ep 1)', 'Deceased'],
       [8, 'Layla El-Faouly', 'Ally', "Archeologist / Marc's Wife",
        'Moon Knight (Ep 2)', 'Active'],
       [9, 'Scarlet Scarab', 'Superhero Identity', 'Avatar of Taweret',
        'Moon Knight (Ep 6)', 'Active'],
       [10, 'Anton Mogart', 'Antagonist', 'Antiquities Collector',
        'Moon Knight (Ep 3)', 'Deceased'],
       [11, 'Crescent Darts', 'Weapon', 'Primary Throwing Weapon',
        'Moon Knight (Ep 1)', 'Active'],
       [12, 'Suit of Armor', 'Equipment', 'Ceremonial Armor of Khonshu',
        'Moon Knight (Ep 1)', 'Active'],
       [13, 'Scarab of Ammit', 'Relic', "Compass to Ammit's Tomb",
        'Moon Knight (Ep 2)', 'Destroyed'],
       [14, 'Ushebti', 'Relic', 'Stone Idol for Bound Deities',
        'Moon Knight (Ep 3)', 'Active']], dtype=object)

In [14]:
df.index.is_unique
df.columns.is_unique

True

> ## **Renaming Columns**

In [15]:
df.sample(10)

,ID,Entity Name,Type,Role / Affiliation,First MCU Appearance,Status
2,3,Jake Lockley,Alter,Ruthless Taxi Driver Alter,Moon Knight (Ep 6),Active
9,10,Anton Mogart,Antagonist,Antiquities Collector,Moon Knight (Ep 3),Deceased
1,2,Steven Grant,Alter,Gift Shop Clerk / Egyptologist,Moon Knight (Ep 1),Active
4,5,Taweret,Ennead Deity,Egyptian Goddess of Childbirth,Moon Knight (Ep 4),Active
8,9,Scarlet Scarab,Superhero Identity,Avatar of Taweret,Moon Knight (Ep 6),Active
0,1,Marc Spector,Alter / Avatar,Primary Avatar of Khonshu,Moon Knight (Ep 1),Active
7,8,Layla El-Faouly,Ally,Archeologist / Marc's Wife,Moon Knight (Ep 2),Active
13,14,Ushebti,Relic,Stone Idol for Bound Deities,Moon Knight (Ep 3),Active
6,7,Arthur Harrow,Avatar / Antagonist,Leader of Ammit Cult,Moon Knight (Ep 1),Deceased
12,13,Scarab of Ammit,Relic,Compass to Ammit's Tomb,Moon Knight (Ep 2),Destroyed

In [16]:
df = df.rename(columns={"id":"Serial"})
df.head()

,ID,Entity Name,Type,Role / Affiliation,First MCU Appearance,Status
0,1,Marc Spector,Alter / Avatar,Primary Avatar of Khonshu,Moon Knight (Ep 1),Active
1,2,Steven Grant,Alter,Gift Shop Clerk / Egyptologist,Moon Knight (Ep 1),Active
2,3,Jake Lockley,Alter,Ruthless Taxi Driver Alter,Moon Knight (Ep 6),Active
3,4,Khonshu,Ennead Deity,Egyptian God of the Moon,Moon Knight (Ep 1),Active
4,5,Taweret,Ennead Deity,Egyptian Goddess of Childbirth,Moon Knight (Ep 4),Active

In [17]:
df = df.rename(columns=str.lower)  # Convert to lowercase
df = df.rename(columns=str.upper)# convert upper
df

,ID,ENTITY NAME,TYPE,ROLE / AFFILIATION,FIRST MCU APPEARANCE,STATUS
0,1,Marc Spector,Alter / Avatar,Primary Avatar of Khonshu,Moon Knight (Ep 1),Active
1,2,Steven Grant,Alter,Gift Shop Clerk / Egyptologist,Moon Knight (Ep 1),Active
2,3,Jake Lockley,Alter,Ruthless Taxi Driver Alter,Moon Knight (Ep 6),Active
3,4,Khonshu,Ennead Deity,Egyptian God of the Moon,Moon Knight (Ep 1),Active
4,5,Taweret,Ennead Deity,Egyptian Goddess of Childbirth,Moon Knight (Ep 4),Active
5,6,Ammit,Ennead Deity,Egyptian Devourer of Souls,Moon Knight (Ep 6),Deceased / Sealed
6,7,Arthur Harrow,Avatar / Antagonist,Leader of Ammit Cult,Moon Knight (Ep 1),Deceased
7,8,Layla El-Faouly,Ally,Archeologist / Marc's Wife,Moon Knight (Ep 2),Active
8,9,Scarlet Scarab,Superhero Identity,Avatar of Taweret,Moon Knight (Ep 6),Active
9,10,Anton Mogart,Antagonist,Antiquities Collector,Moon Knight (Ep 3),Deceased
10,11,Crescent Darts,Weapon,Primary Throwing Weapon,Moon Knight (Ep 1),Active
11,12,Suit of Armor,Equipment,Ceremonial Armor of Khonshu,Moon Knight (Ep 1),Active
12,13,Scarab of Ammit,Relic,Compass to Ammit's Tomb,Moon Knight (Ep 2),Destroyed
13,14,Ushebti,Relic,Stone Idol for Bound Deities,Moon Knight (Ep 3),Active

In [18]:
df = df.rename(columns=str.capitalize)# convert Capitalize
df.head(3)

,Id,Entity name,Type,Role / affiliation,First mcu appearance,Status
0,1,Marc Spector,Alter / Avatar,Primary Avatar of Khonshu,Moon Knight (Ep 1),Active
1,2,Steven Grant,Alter,Gift Shop Clerk / Egyptologist,Moon Knight (Ep 1),Active
2,3,Jake Lockley,Alter,Ruthless Taxi Driver Alter,Moon Knight (Ep 6),Active

> ## **Setting and Resetting Index**

In [19]:
df.columns

Index(['Id', 'Entity name', 'Type', 'Role / affiliation',
       'First mcu appearance', 'Status'],
      dtype='object')

In [20]:
#df = df.set_index('Id')
df.head()

,Id,Entity name,Type,Role / affiliation,First mcu appearance,Status
0,1,Marc Spector,Alter / Avatar,Primary Avatar of Khonshu,Moon Knight (Ep 1),Active
1,2,Steven Grant,Alter,Gift Shop Clerk / Egyptologist,Moon Knight (Ep 1),Active
2,3,Jake Lockley,Alter,Ruthless Taxi Driver Alter,Moon Knight (Ep 6),Active
3,4,Khonshu,Ennead Deity,Egyptian God of the Moon,Moon Knight (Ep 1),Active
4,5,Taweret,Ennead Deity,Egyptian Goddess of Childbirth,Moon Knight (Ep 4),Active

In [21]:
# Reset index (move index back to column)

In [22]:
# Set multiple columns as index
df_multi = df.set_index(['Status', 'Type'])
df_multi.head(15)

                                       Id      Entity name  \
Status            Type
Active            Alter / Avatar        1     Marc Spector
                  Alter                 2     Steven Grant
                  Alter                 3     Jake Lockley
                  Ennead Deity          4          Khonshu
                  Ennead Deity          5          Taweret
Deceased / Sealed Ennead Deity          6            Ammit
Deceased          Avatar / Antagonist   7    Arthur Harrow
Active            Ally                  8  Layla El-Faouly
                  Superhero Identity    9   Scarlet Scarab
Deceased          Antagonist           10     Anton Mogart
Active            Weapon               11   Crescent Darts
                  Equipment            12    Suit of Armor
Destroyed         Relic                13  Scarab of Ammit
Active            Relic                14          Ushebti

                                                   Role / affiliation  \
Status            Type
Active            Alter / Avatar            Primary Avatar of Khonshu
                  Alter                Gift Shop Clerk / Egyptologist
                  Alter                    Ruthless Taxi Driver Alter
                  Ennead Deity               Egyptian God of the Moon
                  Ennead Deity         Egyptian Goddess of Childbirth
Deceased / Sealed Ennead Deity             Egyptian Devourer of Souls
Deceased          Avatar / Antagonist            Leader of Ammit Cult
Active            Ally                     Archeologist / Marc's Wife
                  Superhero Identity                Avatar of Taweret
Deceased          Antagonist                    Antiquities Collector
Active            Weapon                      Primary Throwing Weapon
                  Equipment               Ceremonial Armor of Khonshu
Destroyed         Relic                       Compass to Ammit's Tomb
Active            Relic                  Stone Idol for Bound Deities

                                      First mcu appearance
Status            Type
Active            Alter / Avatar        Moon Knight (Ep 1)
                  Alter                 Moon Knight (Ep 1)
                  Alter                 Moon Knight (Ep 6)
                  Ennead Deity          Moon Knight (Ep 1)
                  Ennead Deity          Moon Knight (Ep 4)
Deceased / Sealed Ennead Deity          Moon Knight (Ep 6)
Deceased          Avatar / Antagonist   Moon Knight (Ep 1)
Active            Ally                  Moon Knight (Ep 2)
                  Superhero Identity    Moon Knight (Ep 6)
Deceased          Antagonist            Moon Knight (Ep 3)
Active            Weapon                Moon Knight (Ep 1)
                  Equipment             Moon Knight (Ep 1)
Destroyed         Relic                 Moon Knight (Ep 2)
Active            Relic                 Moon Knight (Ep 3)

> ## **Basic Attributes Recap**

In [23]:
# Structure
df.shape          # (rows, columns)
df.size           # Total elements
df.ndim           # Number of dimensions

# Components
df.columns        # Column names
df.index          # Row index
df.values         # NumPy array

# Data types
df.dtypes         # Data type per column
df.dtypes.value_counts()  # Count of each data type

# Memory usage
df.memory_usage()  # Memory usage per column
df.memory_usage(deep=True)  # Deep memory usage (includes objects)

Index                    132
Id                       112
Entity name              844
Type                     822
Role / affiliation      1032
First mcu appearance     938
Status                   788
dtype: int64

> ## **Data Selection and Filtering**

In [24]:
df['Type'].head(3)

0    Alter / Avatar
1             Alter
2             Alter
Name: Type, dtype: object

In [25]:
df[['Type' , 'Status']].head(3)

             Type  Status
0  Alter / Avatar  Active
1           Alter  Active
2           Alter  Active

In [26]:
df.Type

0          Alter / Avatar
1                   Alter
2                   Alter
3            Ennead Deity
4            Ennead Deity
5            Ennead Deity
6     Avatar / Antagonist
7                    Ally
8      Superhero Identity
9              Antagonist
10                 Weapon
11              Equipment
12                  Relic
13                  Relic
Name: Type, dtype: object

In [27]:
# selecting row by index
df.iloc[0:10:2]

,Id,Entity name,Type,Role / affiliation,First mcu appearance,Status
0,1,Marc Spector,Alter / Avatar,Primary Avatar of Khonshu,Moon Knight (Ep 1),Active
2,3,Jake Lockley,Alter,Ruthless Taxi Driver Alter,Moon Knight (Ep 6),Active
4,5,Taweret,Ennead Deity,Egyptian Goddess of Childbirth,Moon Knight (Ep 4),Active
6,7,Arthur Harrow,Avatar / Antagonist,Leader of Ammit Cult,Moon Knight (Ep 1),Deceased
8,9,Scarlet Scarab,Superhero Identity,Avatar of Taweret,Moon Knight (Ep 6),Active

In [28]:
# by index label
df.loc[[1,4,8]]

,Id,Entity name,Type,Role / affiliation,First mcu appearance,Status
1,2,Steven Grant,Alter,Gift Shop Clerk / Egyptologist,Moon Knight (Ep 1),Active
4,5,Taweret,Ennead Deity,Egyptian Goddess of Childbirth,Moon Knight (Ep 4),Active
8,9,Scarlet Scarab,Superhero Identity,Avatar of Taweret,Moon Knight (Ep 6),Active

In [29]:
#replacing value
df['First mcu appearance']=df['First mcu appearance'].str.replace("Moon Knight", "" , regex=True)
df['First mcu appearance']=df['First mcu appearance'].str.replace(r'[\(\)]', '', regex=True)

In [30]:
df['First mcu appearance']

0      Ep 1
1      Ep 1
2      Ep 6
3      Ep 1
4      Ep 4
5      Ep 6
6      Ep 1
7      Ep 2
8      Ep 6
9      Ep 3
10     Ep 1
11     Ep 1
12     Ep 2
13     Ep 3
Name: First mcu appearance, dtype: object

In [31]:
df[(df['Status']=='Active') & (df['First mcu appearance']=='Ep 1')]

Empty DataFrame
Columns: [Id, Entity name, Type, Role / affiliation, First mcu appearance, Status]
Index: []

In [32]:
# iloc: Integer position-based indexing
df.iloc[0, 1]        # Row 0, Column 1
df.iloc[0:3, 1:3]    # Rows 0-2, Columns 1-2

    Entity name            Type
0  Marc Spector  Alter / Avatar
1  Steven Grant           Alter
2  Jake Lockley           Alter

> ## **Data Cleaning**

In [33]:
# Check for missing values
print(df.isnull())           # Boolean DataFrame (True where NaN)
print(df.isna())             # Same as isnull()
print(df.isnull().sum())     # Count missing per column
print(df.isnull().any())     # True if any missing in column
print(df.isnull().any().any())  # True if any missing in entire DataFrame

       Id  Entity name   Type  Role / affiliation  First mcu appearance  \
0   False        False  False               False                 False
1   False        False  False               False                 False
2   False        False  False               False                 False
3   False        False  False               False                 False
4   False        False  False               False                 False
5   False        False  False               False                 False
6   False        False  False               False                 False
7   False        False  False               False                 False
8   False        False  False               False                 False
9   False        False  False               False                 False
10  False        False  False               False                 False
11  False        False  False               False                 False
12  False        False  False               False                 False
13  False        False  False               False                 False

    Status
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
10   False
11   False
12   False
13   False
       Id  Entity name   Type  Role / affiliation  First mcu appearance  \
0   False        False  False               False                 False
1   False        False  False               False                 False
2   False        False  False               False                 False
3   False        False  False               False                 False
4   False        False  False               False                 False
5   False        False  False               False                 False
6   False        False  False               False                 False
7   False        False  False               False                 False
8   False        False  False               False                 False
9   False        False  False               False                 False
10  False        False  False               False                 False
11  False        False  False               False                 False
12  False        False  False               False                 False
13  False        False  False               False                 False

    Status
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
10   False
11   False
12   False
13   False
Id                      0
Entity name             0
Type                    0
Role / affiliation      0
First mcu appearance    0
Status                  0
dtype: int64
Id                      False
Entity name             False
Type                    False
Role / affiliation      False
First mcu appearance    False
Status                  False
dtype: bool
False

In [34]:
# Drop missing values
df_clean = df.dropna()              # Drop rows with any NaN
df_clean = df.dropna(axis=1)        # Drop columns with any NaN
df_clean = df.dropna(subset=['Type'])  # Drop rows where Age is NaN
df_clean = df.dropna(how='all')     # Drop rows where ALL values are NaN
df_clean = df.dropna(thresh=2)      # Keep rows with at least 2 non-NaN values

In [35]:
# Fill missing values
df_filled = df.fillna(0)            #

In [36]:

# Forward fill / Backward fill
df_ffill = df.fillna(method='ffill')  # Forward fill (use previous value)
df_bfill = df.fillna(method='bfill')  # Backward fill (use next value)
df_ffill_limit = df.fillna(method='ffill', limit=2)  # Limit forward fill to 2 consecutive NaNs

# Interpolation
df_interp = df.interpolate()  # Linear interpolation

/tmp/ipykernel_830/882399294.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method='ffill')  # Forward fill (use previous value)
/tmp/ipykernel_830/882399294.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df.fillna(method='bfill')  # Backward fill (use next value)
/tmp/ipykernel_830/882399294.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill_limit = df.fillna(method='ffill', limit=2)  # Limit forward fill to 2 consecutive NaNs
/tmp/ipykernel_830/882399294.py:7: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interp = df.interpolate()  # Linear interpolation

> ## **Handling Duplicates**

In [39]:
df.duplicated().sum()

np.int64(0)