<a href="https://colab.research.google.com/github/ariyan378/Data-Analytics-Ml/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)

2.2.2

> ## **Series**

In [2]:
#creating Series
s= pd.Series(['Hridoy' , 'Himu' ])
print(s)

0    Hridoy
1      Himu
dtype: object

In [3]:
#custom index
singer = pd.Series(['Don Toliver' , 'Travis Scott' ,'Future' , "Playboi Carti"] , index=[1,2,3,4])
print(s)

0    Hridoy
1      Himu
dtype: object

In [4]:
#from dictionary

dictionary = {
    1:"No Idea",
    2:"Fein",
    3:"Mask Off",
    4:"Timeless"

}

song = pd.Series(dictionary)
print(song)

1     No Idea
2        Fein
3    Mask Off
4    Timeless
dtype: object

> ## **Data Frame**

In [5]:
# Creating DataFrame from dictionary
data = {
    'Name': ['Himu', 'Hridoy', 'Moon Knight'],
    'Age': [24, 30, 35],
    'City': ['Mirpur', 'Dhaka', 'New York']
}
df = pd.DataFrame(data)
df

          Name  Age      City
0         Himu   24    Mirpur
1       Hridoy   30     Dhaka
2  Moon Knight   35  New York

In [6]:

# From  List
lists = [['Hridoy', 'Data Science'],['Himu' , 'ML Engineer']]
df = pd.DataFrame(data = lists , columns = ['Name' , 'Dream'])
df

     Name         Dream
0  Hridoy  Data Science
1    Himu   ML Engineer

In [7]:
arr = np.arange(1,17).reshape(4,4)
np_df = pd.DataFrame(arr)
np_df

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

> # **Practice Dataset**

In [8]:
#practice dataset
import pandas as pd

# Define the Moon Knight dataset
moon_knight_data = {
    "ID": list(range(1, 15)),
    "Entity Name": [
        "Marc Spector",
        "Steven Grant",
        "Jake Lockley",
        "Khonshu",
        "Taweret",
        "Ammit",
        "Arthur Harrow",
        "Layla El-Faouly",
        "Scarlet Scarab",
        "Anton Mogart",
        "Crescent Darts",
        "Suit of Armor",
        "Scarab of Ammit",
        "Ushebti",
    ],
    "Type": [
        "Alter / Avatar",
        "Alter",
        "Alter",
        "Ennead Deity",
        "Ennead Deity",
        "Ennead Deity",
        "Avatar / Antagonist",
        "Ally",
        "Superhero Identity",
        "Antagonist",
        "Weapon",
        "Equipment",
        "Relic",
        "Relic",
    ],
    "Role / Affiliation": [
        "Primary Avatar of Khonshu",
        "Gift Shop Clerk / Egyptologist",
        "Ruthless Taxi Driver Alter",
        "Egyptian God of the Moon",
        "Egyptian Goddess of Childbirth",
        "Egyptian Devourer of Souls",
        "Leader of Ammit Cult",
        "Archeologist / Marc's Wife",
        "Avatar of Taweret",
        "Antiquities Collector",
        "Primary Throwing Weapon",
        "Ceremonial Armor of Khonshu",
        "Compass to Ammit's Tomb",
        "Stone Idol for Bound Deities",
    ],
    "First MCU Appearance": [
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 6)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 4)",
        "Moon Knight (Ep 6)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 2)",
        "Moon Knight (Ep 6)",
        "Moon Knight (Ep 3)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 1)",
        "Moon Knight (Ep 2)",
        "Moon Knight (Ep 3)",
    ],
    "Status": [
        "Active",
        "Active",
        "Active",
        "Active",
        "Active",
        "Deceased / Sealed",
        "Deceased",
        "Active",
        "Active",
        "Deceased",
        "Active",
        "Active",
        "Destroyed",
        "Active",
    ],
}

# Create DataFrame
df = pd.DataFrame(moon_knight_data)


df.head(2)
# Export to CSV option
# df.to_csv("moon_knight_dataset.csv", index=False)

,ID,Entity Name,Type,Role / Affiliation,First MCU Appearance,Status
0,1,Marc Spector,Alter / Avatar,Primary Avatar of Khonshu,Moon Knight (Ep 1),Active
1,2,Steven Grant,Alter,Gift Shop Clerk / Egyptologist,Moon Knight (Ep 1),Active

In [9]:
print(df.shape)
print(df.columns.to_list())
print(df.size)
print(df.index)
print(df.dtypes)
print(df.info())
print(df.describe(include=['object']))

(14, 6)
['ID', 'Entity Name', 'Type', 'Role / Affiliation', 'First MCU Appearance', 'Status']
84
RangeIndex(start=0, stop=14, step=1)
ID                       int64
Entity Name             object
Type                    object
Role / Affiliation      object
First MCU Appearance    object
Status                  object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    14 non-null     int64
 1   Entity Name           14 non-null     object
 2   Type                  14 non-null     object
 3   Role / Affiliation    14 non-null     object
 4   First MCU Appearance  14 non-null     object
 5   Status                14 non-null     object
dtypes: int64(1), object(5)
memory usage: 804.0+ bytes
None
         Entity Name          Type         Role / Affiliation  \
count             14            14                         14
unique            14            10                         14
top     Marc Spector  Ennead Deity  Primary Avatar of Khonshu
freq               1             3                          1

       First MCU Appearance  Status
count                    14      14
unique                    5       4
top      Moon Knight (Ep 1)  Active
freq                      6      10